### ISSUE TITLE
Wiki update in Server::Installation

### ISSUE THREAD

**Issue by chrisjeon** [bigcommerce/gruf#106]
## Please describe the issue

https://github.com/bigcommerce/gruf/wiki/Server:-Installation

GRPC::RpcServer configuration does not work due to Cannot modify Frozen hash error. It should be something like below.
```
Gruf.configure do |c|
  # The size of the underlying thread pool. No more concurrent requests can be made
  # than the size of the thread pool.
  c.rpc_server_options = c.rpc_server_options.merge({ pool_size: 10 })
end
```

I can't seem to make a PR to make an update. Can someone on the bigcommerce team update the docs? Thanks.

**Comment by splittingred** [comment]
Hi @chrisjeon - Done. Thanks for catching that!
