### ISSUE TITLE
:invalid_request doesn't seem to be a valid error type

### ISSUE THREAD

**Issue by AkihikoITOH** [bigcommerce/gruf#107]
First of all, thank you for creating and maintaining this gem!

While trying it out myself, I realized that calling `fail :invalid_request` [as explained in the Wiki](https://github.com/bigcommerce/gruf/wiki/Server:-Creating-Controllers#custom-field-errors) actually raises an unexpected error `GRPC::Internal: 13:undefined method 'new' for nil:NilClass`.

I think it should be either `fail :invalid_argument` or `fail :bad_request` in this case.

**Comment by splittingred** [comment]
You're right! I've fixed the wiki. Thanks!
