### ISSUE TITLE
fail! raises "NameError: uninitialized constant ActiveSupport::JSON" if active_support/core_ext is required in application

### ISSUE THREAD

**Issue by AkihikoITOH** [bigcommerce/gruf#108]
## Please describe the issue

If an application that uses gruf requires `active_support/core_ext`, the gruf server returns `{ "error": "2 UNKNOWN: NameError: uninitialized constant ActiveSupport::JSON" }` upon `fail! :bad_request`, implying `ActiveSupport::JSON` is somehow unloaded.

With `require 'active_support/core_ext'` commented out, it works just as expected and returns `{ "error": "3 INVALID_ARGUMENT: " }`. Also, requiring `active_support/all` or `active_support/json` won't raise `NameError` and works as expected.

## How to Reproduce

Here are the files that reproduce the behaviour.

#### hello.proto
```proto
syntax = "proto3";

package protos.hello;

service Hello {
  rpc SayHello(HelloInput) returns (HelloOutput) {}
}

message HelloInput {}
message HelloOutput {}
```

#### app.rb
```ruby
require 'gruf'
require 'google/protobuf'

# Returns `{ "error": "2 UNKNOWN: NameError: uninitialized constant ActiveSupport::JSON" }`
require 'active_support/core_ext'

# Fails as expected (`{ "error": "3 INVALID_ARGUMENT: " }`)
# require 'active_support/all'

# Fails as expected (`{ "error": "3 INVALID_ARGUMENT: " }`)
# require 'active_support/json'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('hello.proto', syntax: :proto3) do
    add_message('protos.hello.HelloInput') {}
    add_message 'protos.hello.HelloOutput' do
      optional :message, :string, 1
    end
  end
end

HelloInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('protos.hello.HelloInput').msgclass
HelloOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('protos.hello.HelloOutput').msgclass

class MyService
  include GRPC::GenericService

  self.marshal_class_method = :encode
  self.unmarshal_class_method = :decode
  self.service_name = 'protos.hello.Hello'

  rpc :SayHello, HelloInput, HelloOutput
end

class MyController < ::Gruf::Controllers::Base
  bind MyService

  def say_hello
    fail! :bad_request
  end
end

server = Gruf::Server.new(Gruf.server_options)
Gruf.services.each { |s| server.add_service(s) }
server.start!
```

#### Gemfile
```ruby
gem 'gruf', '2.8.1'
```

#### Gemfile.lock
```
GEM
  specs:
    activesupport (6.0.3.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
      zeitwerk (~> 2.2, >= 2.2.2)
    concurrent-ruby (1.1.6)
    google-protobuf (3.12.1)
    googleapis-common-protos-types (1.0.5)
      google-protobuf (~> 3.11)
    grpc (1.28.0)
      google-protobuf (~> 3.11)
      googleapis-common-protos-types (~> 1.0)
    grpc-tools (1.28.0)
    gruf (2.8.1)
      activesupport (> 4)
      concurrent-ruby (> 1)
      grpc (~> 1.10)
      grpc-tools (~> 1.10)
      slop (~> 4.6)
    i18n (1.8.2)
      concurrent-ruby (~> 1.0)
    minitest (5.14.1)
    slop (4.8.1)
    thread_safe (0.3.6)
    tzinfo (1.2.7)
      thread_safe (~> 0.1)
    zeitwerk (2.3.0)

PLATFORMS
  ruby

DEPENDENCIES
  gruf (= 2.8.1)

BUNDLED WITH
   2.1.4
```

1. `bundle` then `bundle exec ruby app.rb` to start the server on port 9001
2. Call the `SayHello` rpc with an empty message.

## What _should_ happen?

It should return `{ "error": "3 INVALID_ARGUMENT: " }` instead of `{ "error": "2 UNKNOWN: NameError: uninitialized constant ActiveSupport::JSON" }`.

## Anything else we should know?

* Ruby version: 2.6.5
* OS: macOS 10.15.4

The error is raised at https://github.com/bigcommerce/gruf/blob/master/lib/gruf/serializers/errors/json.rb#L31 .
I'm not 100% sure whether this issue is coming from gruf itself, or Active Support, but at least I can confirm that requiring `active_support/json` in gruf itself fixes the issue.

**Comment by splittingred** [comment]
I don't believe this is correct. `gruf` only specifically relies on the [json gem](https://rubygems.org/gems/json) - not the active support extension. We _should_ call that out in the gemspec (i've filed #110 to address that).
