### ISSUE TITLE
The request response is not logged

### ISSUE THREAD

**Issue by namtx** [bigcommerce/gruf#112]
## What? Why?

Describe the problem you are occurring and a proposed solution for it.
I'm using  `Gruf::Interceptors::Instrumentation::RequestLogging::Interceptor` with `formatter: :plain` for request and response logging, but current implementation doesn't log the result value. Is it intended?

Should we add the `result` to log?
## Other Notables

Current source code, it is ignoring the `result` parameter

https://github.com/bigcommerce/gruf/blob/master/lib/gruf/interceptors/instrumentation/request_logging/formatters/plain.rb#L35-L43

**Comment by splittingred** [comment]
Generally we do not log responses to prevent sensitive/PII data from being accidentally/unintentionally leaked into the logs.

I think if someone wanted this functionality, they could create their own formatter, or add to the `plain` one and have it default off.

**Comment by namtx** [comment]
It makes sense 👍
