### ISSUE TITLE
Exception handler for the controller class

### ISSUE THREAD

**Issue by arkdy** [bigcommerce/gruf#117]
## What? Why?

Is there's a way to rescue certain type of exceptions in controller like in Rails `rescue_from`?
If no, could you please point me to the right direction of adding it?

Thanks

**Comment by splittingred** [comment]
Hi @arkdy - no, though there's nothing preventing you from adding `alias_method_chain` or something similar to wrap the method and add a rescue around it. Generally callbacks like that are discouraged as they can hide logic from being explicit, making it more difficult to debug.

If you want something app-wide, a better approach might be to add a ServerInterceptor that then rescues the exceptions there and handles them appropriately.

**Comment by splittingred** [comment]
Closing this due to no response for 1 month. Feel free to re-open to discuss further!
