### ISSUE TITLE
Modify metadata inside client interceptor

### ISSUE THREAD

**Issue by pjo336** [bigcommerce/gruf#119]
## What? Why?

In order to provide a library internally to handle authentication, we would like to implement an interceptor that runs on each client call and appends a JWT to the metadata of the request.

I have not been able to find any examples of modifying the request, just logging based activity. Is an update possible?

**Comment by splittingred** [comment]
:wave: Hi @pjo336! Try something like this:

```ruby
class MyInterceptor < Gruf::Interceptors::ClientInterceptor
  def call(request_context:)
    request_context.metadata[:jwt] = JwtGenerator.build # or whatever code that does this
    yield
  end
end
```

Then in your `Gruf::Client`:

```ruby
client = Gruf::Client.new(
  service: ::MyRpcService,
  options: {
    hostname: "0.0.0.0:9000" # address of service
  },
  client_options: {
    interceptors: [MyInterceptor.new]
  }
)
req = MyReq.new(name: 'foo')
client.call(:MyEndpoint, req)
```

Is that what you're looking for?

**Comment by pjo336** [comment]
That seems exactly like what I am looking for! I must have had a previous issue, bc this was very similar to my first attempt. Thanks for the quick help!

**Comment by abhchand** [comment]
This is really helpful. Adding to metadata is probably one of the most common uses for an interceptor. It might be useful to update [this wiki page](https://github.com/bigcommerce/gruf/wiki/Client%3A-Interceptors) with an explicit example of how to modify `metadata`.

**Comment by splittingred** [comment]
@abhchand Good callout! Done. Thanks for the point-out!
