### ISSUE TITLE
Gruf::Client::Errors::Internal errors

### ISSUE THREAD

**Issue by rahilsondhi** [bigcommerce/gruf#123]
## Please describe the issue

Our web service is sending gRPC requests using Gruf::Client and it's returning a lot of `Gruf::Client::Errors::Internal` errors. 

When I send the same request in a `rails console`, it works fine.

There are no additional messages attached to the exception, and nothing useful in the logs, except a stack trace pointing to https://github.com/bigcommerce/gruf/blob/e88e5827cf4928450c1316c591466cb0c6bcae85/lib/gruf/client.rb#L94

## How to Reproduce

Hard to give repro steps because it works fine in a `rails console`, but in our puma web service, it keeps throwing `Gruf::Client::Errors::Internal` exceptions.

## What _should_ happen?

Either the gRPC requests should succeed, or the `Gruf::Client::Errors::Internal` exceptions should have additional details on why it failed.

## Anything else we should know?

* gRPC version: 1.35.0
* Ruby version: 2.6.3
* OS: `Linux d221dd419d11 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 GNU/Linux`
  * `Debian GNU/Linux 10 \n \l`
* Does it occur at certain traffic volumes, payload size, etc: not that I can tell

**Comment by splittingred** [comment]
Hi @rahilsondhi !

This will be a bit difficult to debug without more information. 

* Can you provide some more code snippets/information on the code path? 
* Does this happen with all gRPC requests with the service? 
* What is this client talking to? (Is it another gruf server or?)
* Is this over TLS or no?
* Do you have any custom interceptors?

Any extra information you have would be helpful. Thanks!

**Comment by rahilsondhi** [comment]
Thanks for the response Shaun! I ended up solving this.

I had a message that was type "any." I thought I could use that for JSON but I was wrong. I changed those fields to "string" (and stringified the JSON) and all is good now. 

A next step would probably be to catch that kind of error and raise a more informative exception. Unfortunately I don't have the bandwidth to contribute that change at the moment.

I appreciate you creating this library! 🙏

**Comment by rahilsondhi** [comment]
Thanks for the response Shaun! I ended up solving this.

I was initializing `Gruf::Client` **in an initializer** and using it as a constant across my app. 

In the web server context, Puma is making new forks of the process, and it turns out gRPC has a problem with this: https://github.com/grpc/grpc/pull/16332

That's why the problem only occurred in the web process, and not in a rails console.

So my solution was to _not_ initialize `Gruf::Client` in an initializer, and instead just lazily initialize it whenever I need to use it.

Thanks for all your work on this library! 🙏
