### ISSUE TITLE
Client timeout less than a second 

### ISSUE THREAD

**Issue by alikinir** [bigcommerce/gruf#126]
Hello , 
I would like to understand why less than a second timeout is not supported ? Is it possible to overcome it ? 
Thank you

**Comment by splittingred** [comment]
@alikinir This seems to be an oversight. I've filed #127 to fix this issue.

**Comment by splittingred** [comment]
This has been resolved in #127 - I'll get a patch release in 2.9.x, and cut the 2.10.0 release, today.

**Comment by splittingred** [comment]
Fixed and released in 
- https://github.com/bigcommerce/gruf/releases/tag/v2.10.0
- https://github.com/bigcommerce/gruf/releases/tag/v2.9.1

**Comment by alikinir** [comment]
Thanks a lot !
