### ISSUE TITLE
StatsD to emit gRPC codes

### ISSUE THREAD

**Issue by Tang8330** [bigcommerce/gruf#130]
## What? Why?

The current StatsD implementation does not include gRPC codes. As part of that, we are bucketing all failures as the same. When `NotFound` vs. `Unknown` or `Internal` should be treated separately.

## Other Notables
![image](https://user-images.githubusercontent.com/4412200/120588137-891c5b80-c3eb-11eb-9102-1aec9c8c0ada.png)

vs.

![image](https://user-images.githubusercontent.com/4412200/120588181-9d605880-c3eb-11eb-9fb8-bc2d7ea28109.png)

**Comment by Tang8330** [comment]
Ping @splittingred - is this something that could get added?

**Comment by splittingred** [comment]
@Tang8330 Apologies for the late reply. No, we don't have plans to augment this - in large scale environments, this would likely overwhelm statsd clusters with high cardinalities of metrics. I'd rather that not live in gruf core.

For a while I've wondered if we should move the statsd metrics out of gruf, and into a plugin like `gruf-statsd`, where more configurations and setups could be supported like this. (Similar to https://github.com/bigcommerce/gruf-prometheus).

I'd rather take that approach. In the meantime, I'd recommend just creating a small interceptor yourself to handle this and add in the appropriate metrics.
