### ISSUE TITLE
GRPC::ActiveCall could not obtain a connection from the pool

### ISSUE THREAD

**Issue by kartickvijayakumar** [bigcommerce/gruf#137]
## Please describe the issue

GRPC::ActiveCall throws a status 13 upon any simple request_response RPC.

`app err:#<GRPC::ActiveCall:0x00007fede59962d8>, status:13:could not obtain a connection from the pool within 5.000 seconds (waited 5.003 seconds); all pooled connections were in use
Sending status  13:could not obtain a connection from the pool within 5.000 seconds (waited 5.003 seconds); all pooled connections were in use`

## How to Reproduce

1. Sync the demo app from https://github.com/bigcommerce/gruf-demo/
2. Instantiate a local mysql2 db server and create a valid user connection
3. Feed the connection URL into .env file
4. Create, Migrate and Seed the db
5. Run 'bundle exec gruf' to start the server
6. Run 'bundle exec rake test:get_product' to instantiate client and hit the server

## What _should_ happen?

A valid response from products table is expected to be returned on the get_product RPC call.
However, we always get the below error:
`app err:#<GRPC::ActiveCall:0x00007fede59962d8>, status:13:could not obtain a connection from the pool within 5.000 seconds (waited 5.003 seconds); all pooled connections were in use
Sending status  13:could not obtain a connection from the pool within 5.000 seconds (waited 5.003 seconds); all pooled connections were in use`

The DB connections and controller configurations are fine on the rails APP. Confirmed this through the rails console
`irb(main):118:0> Product.first`
`Product Load (4.5ms)  SELECT 'products'.* FROM 'products' ORDER BY 'products'.'id' ASC LIMIT 1`
`=> #<Product:0x00007fd41aa275b0 id: 1, name: "Small Bronze Shirt", price: 34.78, created_at: Sat, 27 Nov 2021 08:21:52.000000000 UTC +00:00, updated_at: Sat, 27 Nov 2021 08:21:52.000000000 UTC +00:00>`

## Anything else we should know?

* Ruby version - 2.7.5 and 3.0.3
* OS - MacOS
* Happens every time

**Comment by kartickvijayakumar** [comment]
@splittingred can you help with this?

**Comment by billthompson** [comment]
@kartickvijayakumar I was not able to replicate this issue, so I'd like to get more information from mysql. Once you are in a situation where you can replicate this error consistently, can you provide the output from the following commands?

1. `mysql -u [USER] -p -v` - Outputs the mysql version
2. `show variables like "max_connections";` - Get the max number of connections allowed by mysqld
3. `show status like 'Conn%';` - Get the number of connections we have established

**Comment by kartickvijayakumar** [comment]
1) ---- MySQL version ----
`gruf-demo kartickv$ mysql -u kartickv -p -v`
`Enter password:`
`Welcome to the MySQL monitor.  Commands end with ; or \g.`
`Your MySQL connection id is 211`
`Server version: 8.0.27 Homebrew`

2 --- Max connections ----
`mysql> show variables like "max_connections";`
`--------------`
`show variables like "max_connections"`
`--------------`
`+-----------------+-------+`
`| Variable_name   | Value |`
`+-----------------+-------+`
`| max_connections | 250   |`
`+-----------------+-------+`
`1 row in set (0.08 sec)`

3) --- Number of connections ----
`mysql> show status like 'Conn%';`
`--------------`
`show status like 'Conn%'`
`--------------`
`+-----------------------------------+-------+`
`| Variable_name                     | Value |`
`+-----------------------------------+-------+`
`| Connection_errors_accept          | 0     |`
`| Connection_errors_internal        | 0     |`
`| Connection_errors_max_connections | 0     |`
`| Connection_errors_peer_address    | 0     |`
`| Connection_errors_select          | 0     |`
`| Connection_errors_tcpwrap         | 0     |`
`| Connections                       | 213   |`
`+-----------------------------------+-------+`
`7 rows in set (0.03 sec)`

**Comment by kartickvijayakumar** [comment]
I'm stuck at the same place. Unable to find out from where the `app err` error is popping up. [GRPC::ActiveCall](https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/generic/active_call.rb) seems to be the only hint but that isn't leading me anywhere either.

Somehow I have a vague feeling this error isn't due to DB connections. I simply ran `puts Product.first.inspect` in my gruf initiallizers and a few other places - the result is being appropriately fetched from DB.

But when an actual rpc request comes through, after all the interceptors have executed somewhere between gruf and grpc framework calls, the request's ActiveCall seems to be erroring out. Control never reaches my controller methods.

**Comment by splittingred** [comment]
I cannot replicate this (nor can any of our end-to-end test suites for the gruf project) - this looks to me like a mysql misconfiguration, or local environment issue.

This sounds like you have a rogue process also bound to that port, somehow. Can you run `lsof -i :10541` and see what shows up? Also, `all pooled connections were in use` is an ActiveRecord issue, not a grpc (or gruf) issue.

**Comment by splittingred** [comment]
This issue has become stale, closing for now. Feel free to re-open after answering the above question and providing replication steps. Thanks!
