### ISSUE TITLE
Gruf 2.13 with gRPC 1.42 causes an error and prevents RSpec from shutting down

### ISSUE THREAD

**Issue by hosamaly** [bigcommerce/gruf#149]
## Please describe the issue

With Gruf 2.13 and GRPC 1.42 (and 1.43), running an RSpec test that initializes a `Gruf::Client` causes errors to be printed and RSpec to hang after the test and never shut down.

The output of the test below looks like this:
```
E0303 17:27:48.186961000 4570361344 dns_resolver_ares.cc:450]          no server name supplied in dns URI
E0303 17:27:48.187024000 4570361344 channel.cc:77]                     channel stack builder failed: {"created":"@1646328468.187000000","description":"the target uri is not valid: dns:///","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":1094}
.

Finished in 0.0046 seconds (files took 0.41242 seconds to load)
1 example, 0 failures

^C
RSpec is shutting down and will print the summary report... Interrupt again to force quit.
^C
```

Those `^C` are my keypresses trying to shut it down.

## How to Reproduce

Using this Gemfile:
```ruby
source 'https://rubygems.org'

gem 'gruf', '2.13.1'
gem 'grpc', '>= 1.42.0'
gem 'rspec'
```

And this test file:
```ruby
require 'gruf'

module Example
  class Service
    include GRPC::GenericService
  end

  Stub = Service.rpc_stub_class
end

RSpec.describe Gruf::Client do
  it 'works' do
    Gruf::Client.new(service: Example)
  end
end
```

Run:
```sh
bundle && bundle exec rspec *_spec.rb
```

## What _should_ happen?

There should be no errors. And after reporting success, RSpec should exit.

## Anything else we should know?

* gRPC version: 1.42 and 1.43.1
* Ruby version: 2.7.5
* OS: Mac

**Comment by splittingred** [comment]
Hi @hosamaly - this is likely a core grpc issue, but I noticed it seems you're not specifying a hostname, which may cause issues with the channel creation. What happens if you do:

```ruby
Gruf::Client.new(service: Example, options: { hostname: '127.0.0.1:8000' })
```

**Comment by hosamaly** [comment]
Indeed, specifying the hostname fixes the issue. Thanks!

Perhaps `Gruf::Client#initialize` should require a `hostname`. It currently defaults it to `Gruf.default_client_host`, which defaults to an empty string. But with the new validation in gRPC v1.42, `Gruf.default_client_host = ''` is no longer valid.
