### ISSUE TITLE
Please release 2.13.2

### ISSUE THREAD

**Issue by jamesmoriarty** [bigcommerce/gruf#152]
## What? Why?

Support for [Ruby 3.1 has been merged here](https://github.com/bigcommerce/gruf/commit/a6d649da4c5bf8045630469e28f5f029c6842839) but is unreleased. Could you please release a new version of the gem.

**Comment by splittingred** [comment]
Hi @jamesmoriarty - sorry, this dropped off my radar, will get this done tomorrow. Thanks for the nudge.

**Comment by jamesmoriarty** [comment]
No worries. Thanks for maintaining gruf.

**Comment by achhetr** [comment]
Super quick response @splittingred :)

**Comment by splittingred** [comment]
@jamesmoriarty Not a problem, my pleasure to do so.

FYI:
https://rubygems.org/gems/gruf/versions/2.14.0
https://github.com/bigcommerce/gruf/releases/tag/v2.14.0
