### ISSUE TITLE
Next step in `Server:-Creating-Controllers.md` not linked

### ISSUE THREAD

**Issue by ryy** [bigcommerce/gruf#155]
## What? Why?
Hi👋 bigcommerce team.

I found something very small.

As I was going through the tutorial, I noticed that the `Next: [Running Gruf and Command Line Options]` link at the end of the page was not done.

Unfortunately, it seems difficult to pull requests for wiki content, so I'll just present a diff.

- https://github.com/bigcommerce/gruf/wiki/Server:-Creating-Controllers
```diff
- Next: [Running Gruf and Command Line Options]
+ Next: [Running Gruf and Command Line Options](https://github.com/bigcommerce/gruf/wiki/Server:-Running-Gruf-and-Command-Line-Options)
```

## Other Notables

- N/A

**Comment by splittingred** [comment]
Thanks @ryy! I've fixed the link. Appreciate the catch.
