### ISSUE TITLE
Starting Gruf and bind with specific controllers

### ISSUE THREAD

**Issue by Loschcode** [bigcommerce/gruf#156]
Is there a way with Gruf to start a server and bind it to a set of specific controllers within the codebase? I'm currently working on implementing this into a monolith and we would like to have some flexibility regarding what's listened to or not.

```
# example
bundle exec gruf --only=RoleAndPermissionsController
```

Or something of sort, so that the gRPC server doesn't listen to other services when being started.

**Comment by splittingred** [comment]
Hello @Loschcode - there's not a filtered controller argument on the binstub, but you could easily copy the binstub: https://github.com/bigcommerce/gruf/blob/main/bin/gruf and then pass appropriate arguments into the CLI executor:

```ruby
cli = Gruf::Cli::Executor.new(services: [::MyRoleAndPermissionsRpcService])
cli.run
```

That would achieve what you're trying to do.

**Comment by trickleup** [comment]
In this case, when running potentially multiple instances of gruf from the same code base, what's the best practice of isolating configuration between the different instances? E.g. it seems like when using:

```
Gruf.configure do |c|
  # ...
```

... then this configuration will apply to all instances of the `Gruf::Cli::Executor` that are created. I wonder what is the best way to separate them.

**Comment by splittingred** [comment]
@trickleup `Gruf::Cli::Executor.new` has a `services:` argument you can use, which the executor will _only_ use those services if passed. `Gruf.services` only is used if `services:` there is empty.

**Comment by splittingred** [comment]
Released in https://github.com/bigcommerce/gruf/releases/tag/v2.16.0
