### ISSUE TITLE
Request context for interceptors to communicate information back to controllers

### ISSUE THREAD

**Issue by trickleup** [bigcommerce/gruf#163]
I'm writing interceptor code to parse an access token, and communicate back the parsed token object to the gruf controller, in some capacity, that is only visible in the scope of a single request. Ideally, I would like to set the data in an interceptor, something like:

```
request.context['parsed_token'] = parse_token(token_str)
```

And then access this object in a controller, like:

```
ctx = request.context['parsed_token']
parsed_token.some_value
```

I can accomplish this with `request.active_call.metadata`, but that will (I think) communicate the data back to the client, which is not the intent. It's solely meant as an internal convenience, and to make sure the token isn't parsed more than once. I have to parse it in the interceptor, regardless.

Does gruf provide something like that, or am i thinking of this the wrong way?

Thanks for a great library.

**Comment by splittingred** [comment]
Hi @trickleup - Unfortunately there's not a clean way to do this at present without modifying the metadata. This would be a fairly simple feature to add to the `Gruf::Controllers::Request` object; we'll look into it for the next release.

**Comment by splittingred** [comment]
Released in https://github.com/bigcommerce/gruf/releases/tag/v2.16.0
