### ISSUE TITLE
Minor typo in wiki, recommended fix :)

### ISSUE THREAD

**Issue by hernanat** [bigcommerce/gruf#170]
## Please describe the issue

The [Creating Controllers](https://github.com/bigcommerce/gruf/wiki/Server:-Creating-Controllers) step of the wiki has a minor typo:

<img width="865" alt="Screen Shot 2022-09-16 at 11 14 13 AM" src="https://user-images.githubusercontent.com/20129498/190705300-a1001a44-32ec-4240-a3af-d0e07f97b114.png">

i.e. `Demo::JobController` should be `Demo::JobsController`
## How to Reproduce

**Comment by TomA-R** [comment]
Hi @hernanat,

Nice catch, thanks for reporting! This has been updated:

<img width="830" alt="Screen Shot 2022-09-18 at 4 42 21 pm" src="https://user-images.githubusercontent.com/1606901/190889352-8963b8c2-1d46-442c-b3f4-c1b40d66d7b7.png">
