### ISSUE TITLE
Ruby does not generate correct proto with ruby version 3.1.0 and 3.2.0

### ISSUE THREAD

**Issue by miklblitz** [bigcommerce/gruf#192]
## Please describe the issue

with ruby 3.1.0 and 3.2.0

command 

grpc_tools_ruby_protoc --ruby_out=app/proto --grpc_out=app/proto Categories.proto

generate bad proto file

```
descriptor_data = "\n\x10\x43\x61tegories.proto\x12\x03rpc\"E\n\x08\x43\x61tegory\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04sort\x18\x03 \x01(\r\x12\x10\n\x08jsondata\x18\x04 \x01(\t\"1\n\x10GetCategoriesReq\x12\x0e\n\x06search\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\r2G\n\nCategories\x12\x39\n\rGetCategories\x12\x15.rpc.GetCategoriesReq\x1a\r.rpc.Category\"\x00\x30\x01\x62\x06proto3"
```

with  version 3.0.1 everythin works OK

## How to Reproduce

1. Install RubyOnRails 7.0.4 and gems gruf 2.17.0
2. generate  proto

## What _should_ happen?

expected correct proto file but i ll get invalid proto file

## Anything else we should know?

* gRPC version - gruf (2.17.0)
* Ruby version -  3.1.0 or 3.2.0
* OS - Ubuntu

**Comment by miklblitz** [comment]
problem will be solved if explicitly add into Gemfile:
```
gem 'grpc', '~> 1.52.0'
gem 'grpc-tools', '~> 1.52.0'
```

and command
```
bundle exec grpc_tools_ruby_protoc --version
```
have to answer:
libprotoc 3.21.6

**Comment by splittingred** [comment]
Hi @miklblitz - this is related to the grpc gem, not to gruf. Thanks!
