### ISSUE TITLE
Wiki: update instrumentation docs to rename blacklist to blocklist, since that's what it is in the code.

### ISSUE THREAD

**Issue by samsarkleio** [bigcommerce/gruf#200]
## Please describe the issue

The code will read from a setting called `blocklist`; however, the documentation [here](https://github.com/bigcommerce/gruf/wiki/Server:-Instrumentation-and-Logging) refers to it as `blacklist`.

## How to Reproduce

See https://github.com/bigcommerce/gruf/wiki/Server:-Instrumentation-and-Logging and search for `blacklist`.

## What _should_ happen?

Wiki should be updated. I'd submit a PR but I don't have access.

**Comment by splittingred** [comment]
Done, thanks!
