### ISSUE TITLE
Gruf server stuck at starting

### ISSUE THREAD

**Issue by Abdullah-l** [bigcommerce/gruf#204]
## Please describe the issue
`bundle exec gruf` terminates immediately after running without any logs. So I tried with the CLI, and it seems to get stuck at starting:
```
2.7.7 :001 > cli = Gruf::Cli::Executor.new(services: [::Foo::Service])
 => #<Gruf::Cli::Executor:0x0000000124945780 @args=[], @options=#<Slop::Result:0x00000001249379f0 @parser=#<Slop::Parser:0x0000000124945488... 
2.7.7 :002 > cli.run
2024-02-03 22:50:40.946095 D [10474:16560 base.rb:67] Rails -- [gruf] Binding Foo::Service to FooController
2024-02-03 22:50:40.949645 I [10474:74320 server.rb:96] Rails -- [gruf] Starting gruf server at 0.0.0.0:9001...
```

is there a way to debug why the gruf server isn't starting? I also tried a different port and url

## What _should_ happen?

Start

## Anything else we should know?

* gRPC version 1.60
* Ruby version 2.7.7
* OS macos 14.1
* Does it occur at certain traffic volumes, payload size, etc

**Comment by splittingred** [comment]
Hi @Abdullah-l - if your LOG_LEVEL is set low enough, the "Starting gruf server" will be the last line you see. Have you tried issuing requests against it?

Also, we recommend upgrading to a non-EOL Ruby - 2.7 is no longer supported.
