### ISSUE TITLE
Gruf logs `Grpc::InvalidArgument` as an error rather than info

### ISSUE THREAD

**Issue by pedelman** [bigcommerce/gruf#49]
When utilizing the Gruf request logger, when the service raises a `Grpc::InvalidArgument`, Gruf is marking that as an `error` severity.

I consider `InvalidArgument` to be more of an "allowed" or "expected" behavior, and shouldn't be logged at such a severity. I propose we would handle this error as `info` level.

```rb
fail!(:bad_request, :bad_request, 'Bad Request')
```

Code that determine the log severity: [lib/gruf/interceptors/instrumentation/request_logging/interceptor.rb#L52-L58](https://github.com/bigcommerce/gruf/blob/master/lib/gruf/interceptors/instrumentation/request_logging/interceptor.rb#L52-L58)

**Comment by splittingred** [comment]
Fixed in #51, released in 2.4.0
