### ISSUE TITLE
Explicit render support

### ISSUE THREAD

**Issue by arr-dev** [bigcommerce/gruf#50]
Current way of rendering values returned from Gruf controller action makes it impossible to use [wisper gem](https://github.com/krisleech/wisper) in Gruf controllers.

In order to use `wisper` it would need some explicit render support, similar to what rails does.
Example from [wisper docs](https://github.com/krisleech/wisper#actioncontroller)

Calling `return` in wisper callback blocks can't work due to way [ruby handles blocks](https://product.reverb.com/the-strange-case-of-wisper-and-ruby-blocks-behaving-like-procs-be130f9fa04a)

**Comment by splittingred** [comment]
This seems to me to be more a limitation of Wisper and less of gruf.

The gRPC specification is pretty clear that gRPC methods should _return_ their response objects; I'd rather not deviate from that.
