### ISSUE TITLE
Ability to generate code automatically with the gruf binary

### ISSUE THREAD

**Issue by nocivus** [bigcommerce/gruf#67]
## What? Why?
Would be nice to have gruf regenerate the service code when we run `gruf`.

Proposed solution: Something like adding this either to the binary, or to the executor:
```
`rm -rf app/rpc/generated/*`
Dir[File.expand_path "./app/rpc/**/*.proto"].each do |proto|
  absolute_path = Pathname.new(File.expand_path(proto))
  project_path  = Pathname.new(File.join(__dir__, ".."))
  relative_proto = absolute_path.relative_path_from(project_path)
  `grpc_tools_ruby_protoc -I "./app/rpc" --ruby_out="app/rpc/generated" --grpc_out="app/rpc/generated" #{relative_proto}`
end
```

**Comment by splittingred** [comment]
Hey! Thanks for filing. I'd prefer to keep code generation out of gruf - that's not really its intent or purpose.

I'm also a bigger proponent of a centralized, separated service definition library (as opposed to packaging in protos into the service's repo). I'd rather us not have gruf couple those two concepts together, or force direction there. Our best practice at BC recommends having a centralized definition library that bundles the protos as a gem, then you include it with gruf in your service.

Thanks! Closing this as won't fix.
