### ISSUE TITLE
Not clear how to implement client

### ISSUE THREAD

**Issue by quinn** [bigcommerce/gruf#75]
It's unclear where to instantiate a client. Not in the initializer apparently, thats just where defaults are set. 

Do you instantiate a new client stub for every call you are making to a GRPC service?

**Comment by quinn** [comment]
like, this code example is completely useless:

```ruby
require 'gruf'

id = args[:id].to_i.presence || 1

begin
  client = ::Gruf::Client.new(service: ::Demo::ThingService)
  response = client.call(:GetMyThing, id: id)
  puts response.message.inspect
rescue Gruf::Client::Error => e
  puts e.error.inspect
end
```

Does that go in every place in the code, immediately before calling the client? I highly doubt it. You're assigning the client to a local var. Does this mean that every instance of a client is used for only one RPC call? Its very misleading / useless code example.

**Comment by splittingred** [comment]
Hi @quinn - apologies for the lack of docs! Yes, we probably can add more here, but generally gruf follows the same concepts and behaviors as the [Ruby gRPC client](https://grpc.io/docs/quickstart/ruby/), which is where you instantiate a client object paired with a service stub, and then call actions on it.

You can make separate calls by just calling the `call` method on the client multiple times, or call different methods. Similarly, you can use [dependency injection](https://dry-rb.org/gems/dry-container/) to store an instance of the client app-wide, if you don't want to instantiate it in a class. Gruf is purposely unopinionated on this, to allow for flexibility in upstream systems.

**Comment by splittingred** [comment]
Hi @quinn - I've added a wiki to the gruf repo: https://github.com/bigcommerce/gruf/wiki

You can find information about client creation here: https://github.com/bigcommerce/gruf/wiki/Client%3A-Installation and following.

This should have plenty of detail to get you started. I'll keep augmenting this further in the next few weeks. Thanks for the feedback!
