### ISSUE TITLE
Question: is it easier to use gruf with rails or not?

### ISSUE THREAD

**Issue by phanpak** [bigcommerce/gruf#83]
Note: this is not an issue per se, it's more of a general question. Let me know if this is not the best place to do this.

Hey guys,

I'm about to implement a gRPC service using ruby. gruf seems to be a great addition to achieve that goal. 

I'm pondering whether I should use gruf with rails or not. What would be the main benefit of doing it? My service will be stateless, without a DB and not an http server. I see that gruf is supposed to be framework agnostic but a lot of the documentation is using examples inside rails apps. So I'm wondering if using gruf along with rails might be smoother.

**Comment by splittingred** [comment]
Hi @phanpak - it's pretty unopinionated. We at bigcommerce are using gruf with both Rails, Grape, and native Ruby apps, without issue. The big caveat to not using Rails is you'll need to probably ensure order of loading and execution works - specifically the binding of the server stubs to the gruf controllers. It will depend on how your non-rails system is loading things. 

You can also just not use the gruf binstub and run the CLI executor directly:

```ruby
require 'rubygems'
require 'bundler/setup'
require 'gruf'

cli = Gruf::Cli::Executor.new
cli.run
```

I prefer using a stripped-down Rails for the ActiveRecord, initializer, settings, and testing support, but YMMV, and again - gruf is really not opinionated here. Thanks!

**Comment by phanpak** [comment]
@splittingred thank you for the reply. I think your point about using a stripped-down version of Rails makes sense.
