### ISSUE TITLE
`uninitialized constant PackageModule::GeneratedModule::Service`

### ISSUE THREAD

**Issue by yoavgray** [bigcommerce/gruf#84]
## Please describe the issue

I followed the wiki and created a very small proto file with a package, service and `Req` & `Resp` messages. Then I generated the stubs and created a controller but no matter what I do, when I run `bundle exec gruf` and tries to load the controller, it errors on the `bind` call saying:
`NameError: uninitialized constant PackageModule::GeneratedModule::Service`

## How to Reproduce

1. Follow the Wiki
2. Run Gruf
3. See error

## What _should_ happen?

Not sure :)

## Anything else we should know?

* gRPC version 1.22.0
* Ruby version 2.6.2
* Rails version 5.2.3
* OS MacOs

**Comment by splittingred** [comment]
Hello @yoavgray - did you happen to `require` the generated service stub classes?

**Comment by yoavgray** [comment]
Hi @splittingred, I haven't, but I also don't see it being called anywhere in the demo so I figured it's not necessary. What am I missing?

**Comment by splittingred** [comment]
You'll need to require the generated pb files, such as is done here: https://github.com/bigcommerce/gruf-demo/blob/master/config/initializers/gruf.rb#L2

You can either manually require them, have them generate into a directory and load all `_services_pb` files, or use a gem (what we do at BigCommerce) to load them dynamically:

```ruby
path = '/path/to/generated/files'
$LOAD_PATH.unshift(path) unless $LOAD_PATH.include?(path)
Dir.glob("#{path}/**/*_services_pb.rb").each do |path|
  load path
end
```

**Comment by yoavgray** [comment]
Ok, thanks for the detailed response. I'll give it a try and update.

**Comment by splittingred** [comment]
Sounds good @yoavgray - I'm going to close this issue. Feel free to re-open if you encounter another issue.
