### ISSUE TITLE
Idea: Refactoring TLS options/configuration/etc.

### ISSUE THREAD

**Issue by jgarber623** [bigcommerce/gruf#85]
Hello! I recently came across Gruf and I'm really enjoying using it with some gRPC services we're implementing at work. Thank you for your hard work on this gem!

### Background

I started digging in to the `build_ssl_credentials` to determine how the gem creates instances of `GRPC::Core::ChannelCredentials` (the [relevant lines in `client.rb`](https://github.com/bigcommerce/gruf/blob/master/lib/gruf/client.rb#L192-L201)).

Gruf currently supports passing a path to a file (`ssl_certificate_file`) or a string representing a single certificate (`ssl_certificate`). Both are coerced and passed to `GRPC::Core::ChannelCredentials.new` as a single argument.

This behavior maps to one of several cases supported by the `GRPC::Core::ChannelCredentials`. That class itself is generated on-the-fly (I think…), but we can infer what it supports from [the class' specs](https://github.com/grpc/grpc/blob/master/src/ruby/spec/channel_credentials_spec.rb). The cases in the specs show that the class can take no arguments, one argument (as supported by Gruf), and three arguments (PEM-encoded root certificate, client key, and client certificate).

### Question/Idea/Feature Request

**Would it be reasonable to modify Gruf to support the latter case?** Possibly having a new option (e.g. `certificate_list`) that is an Array that `build_ssl_credentials` passes as arguments to `GRPC::Core::ChannelCredentials`?

Or, a broader refactoring that allows for more declarative specification of root certificate, client key, and client certificate could be useful, too.

_Edit:_ Another idea: would it be reasonable to also allow passing an existing `GRPC::Core::ChannelCredentials` instance?

I'm not terribly familiar with C, but I _think_ these are the relevant lines demonstrating how the GRPC gem handles channel credential creation in [`grpc/src/ruby/ext/grpc/rb_channel_credentials.h`](https://github.com/grpc/grpc/blob/master/src/ruby/ext/grpc/rb_channel_credentials.c#L145-L185).

If one or more of the above ideas seems reasonable, I'd be happy to put together a PR for feedback. Let me know what y'all think and thanks for your time!

**Comment by splittingred** [comment]
I think allowing passing a `GRPC::Core::ChannelCredentials` is reasonable, as long as we maintain backwards support for the current implementation.

Off-hand, I'd personally recommend not allowing raw gRPC servers to serve SSL, and instead managing that through a service mesh like [linkerd](http://linkerd.io/) or [envoy](https://www.envoyproxy.io/), so you can properly LB and reduce the impact of TLS encryption to the edge.
