### ISSUE TITLE
Support Rails code reloading in Dev env

### ISSUE THREAD

**Issue by ocha** [bigcommerce/gruf#86]
## What? Why?

Rails framework automatically reloads code when it is changed in dev environment. That enables developer to see changes right away without need of restarting the server. It would make development process much faster and easier, if within Rails framework, gruf could use reloaded code.

## Other Notables

Starting Rails 5, there are helpers to deal with thread safety and code reloading. Other multi-threaded gems that integrate with Rails, use these helpers to enable code reloading in dev env. Refer to https://guides.rubyonrails.org/threading_and_code_execution.html#reloader and https://github.com/mperham/sidekiq/commit/be2d12912ebe7aa074afbbd7e16f60259848ec91

**Comment by splittingred** [comment]
I think this is a good idea to support; however, due to the way gRPC's thread pool works, I'm not sure just dumping the executor or interlock before a controller call will work (my initial tests at this a few months ago didn't work with it).

Thoughts?

**Comment by ocha** [comment]
I have not tried out Rails Reloader yet, but from what I saw in docs, my understanding is that we need to wrap a code with Reloader before starting new threads. My guess is that if we wrap gruf server (before it starts the grpc threads), it might just work.

https://github.com/bigcommerce/gruf/blob/195465cf376bf3439d7b02da4ae290b8771c010c/lib/gruf/server.rb#L56

**Comment by splittingred** [comment]
Unfortunately, it doesn't in my testing. (Wrapping the server start! thread starts and joins doesn't.)

**Comment by ocha** [comment]
ok. so it seems it will need something more. I can try to experiment on it this weekend and see if I can uncover something

**Comment by splittingred** [comment]
My guess is it's the way gRPC manages its thread queue separate from the server thread, and the loading of that isn't triggering with the built-in rails classes.

**Comment by ocha** [comment]
I was able to look into this over the weekend, and there is one big issue. All interceptors and grpc controllers are instantiated during bootup which does not work with code reloading. I was able to trigger code reloading, but I got an error that there was reference to previous instance of the class. If grpc was creating a new instance of interceptors and controllers when request is being processed, then this would be very easy. Until that part in grpc is changed, I dont think code reloading would be possible without heavy patching of grpc.

**Comment by splittingred** [comment]
This has now been accomplished for gruf controllers in https://github.com/bigcommerce/gruf/releases/tag/v2.15.0 - note you'll need to remove `app/rpc` from any zeitwerk management you may be doing in your apps if you were doing it as a stop-gap. Feel free to re-open if you find any issues or extra functionality you'd like!

**Comment by Freubert** [comment]
Is there a way to also reload other folders than `app/rpc` when on Rails? I can see that the Rails zeitwerk reloading is enabled for the known Rails folders (like `app/models`), but the reload is not triggered when running on gruf.
