### ISSUE TITLE
Integration testing guide for `Gruf::Client`  

### ISSUE THREAD

**Issue by timbogit** [bigcommerce/gruf#88]
## What? Why?

It would be great to have some guidance around stubbing out downstream gRPC calls in test code of applications that use `Gruf::Client`. 
In traditional (RESTful) scenarios, tools like [`vcr`](https://github.com/vcr/vcr) or [`WebMock`](https://github.com/bblimke/webmock) to prerecord / mock out downstream HTTP requests.

Spelunking in the `gruf` code itself, it looks like one can always create `Gruf::Client` instances with [mocked-out `#call` methods](https://github.com/bigcommerce/gruf/blob/60a30c800ff16de05e74b8ef7af58f5deae521ef/spec/gruf/client_spec.rb#L103-L128) for specs, which then return [prefabricated `Gruf::Response`](https://github.com/bigcommerce/gruf/blob/21a0eb4854bf772ce54ec46635f8226e11ed9c4a/spec/gruf/response_spec.rb#L27-L53) results. That said, it would be great to have a dedicated documentation section somewhere (on the Wiki?) to give guidance and/or example code for a recommended approach.

**Comment by Beans0063** [comment]
I'm also in search of some guidance on testing.  @timbogit are you suggesting to patch the client like below?  This was successful for me to bypass the wire and return an expected response.  But feels like a workaround that won't scale so well.  

Any other advice from Gruf team or others?  Thanks.

```
module Gruf
  class Client
    def call(request_method, params = {}, metadata = {}, opts = {}, &block)
      Myservice::MyResult.new({my_param: 0})
    end
  end
end
```

**Comment by splittingred** [comment]
Hi ya'll! With regards to general testing in gruf, there is [gruf-rspec](https://github.com/bigcommerce/gruf-rspec), which assists with server responses. As for handling clients, the best way to handle this is [dependency injection](https://en.wikipedia.org/wiki/Dependency_injection). 

Here's some examples of how we handle it at BigCommerce. Let's say you have an `Services::Accounts::Service` gRPC service. You can extend Gruf::Client like so:

```ruby
module Accounts
  class Client < ::Gruf::Client
    def initialize(hostname:, options: {})
      opts = {
        service: ::Services::Accounts,
        options: {
          hostname: hostname # and other things if needed
        }
      }.merge(options)
      super(opts)
    end
  end
end
```

From there, you inject it into your service class:

```ruby
module Accounts
  class Service
    def initialize(client: nil)
      @client = client || Accounts::Client.new(hostname: 'my.hostname:1234')
    end
    
    def create(name:)
      response = @client.call(:CreateAccount, name: name.to_s)
      AccountEntity.new(name: response.message.name)
    rescue Gruf::Client::Error => e
      raise Accounts::Errors::FailedCreation, e.message
    end
  end
end
```
 
Or something similar. From there, you can just inject a dummy client in tests:

```ruby
describe Accounts::Service
  let(:service) { described_class.new(client: client) }
  let(:client) { double(:client, call: call_result) }

  describe '#create' do
    let(:name) { "Bob's Burgers" }
    let(:call_result) { CreateAccountResp.new(name: name) }

    subject { service.create(name: name) }

    it 'should create the account' do
      expect(subject).to be_a(AccountEntity)
      expect(subject.name).to eq name
    end
  end
end
```

That's generally how we handle it. I highly recommend using something like [dry-system](https://dry-rb.org/gems/dry-system/0.12/) for dependency injection, but there's nothing saying you can't wire that up manually.

**Comment by timbogit** [comment]
Thanks, @splittingred ! This is great advice, and thanks also for showing the real-world example of what you all do at BigCommerce.

Would it be worth adding something along those lines to the Wiki?

**Comment by splittingred** [comment]
@timbogit Happy to. Will get to that later today.

**Comment by splittingred** [comment]
I've copied this over to the wiki: https://github.com/bigcommerce/gruf/wiki/Client:-Testing

Will look at expanding it a bit more after the holidays. Thanks for raising this issue! Closing for now.
