### ISSUE TITLE
Allow custom payload in request logger

### ISSUE THREAD

**Issue by zinosama** [bigcommerce/gruf#92]
## What? Why?

My API response has some custom data fields that I'd like to add to the request logs. However, I don't see any way of extending the current request log payload. Would it make sense to provide a way for user to define custom payload that gets merged into the default payload for request logs?

If this makes sense to folks, I'm happy to try and submit a PR on this. I'm also happy to hear any work-around for this.

**Comment by splittingred** [comment]
There's not out of the box. It might be a good option. That said, you could fairly easily create a custom formatter:

```ruby
require 'gruf'

class MyCustomFormatter < Gruf::Interceptors::Instrumentation::RequestLogging::Formatters::Base
  def format(payload)
    # do custom payload things here
    payload.merge!(format: 'json')
    payload.to_json
  end
end

Gruf.configure do |c|
  c.interceptors.use(
    Gruf::Interceptors::Instrumentation::RequestLogging::Interceptor,
    formatter: MyCustomFormatter
  )
end
```

**Comment by zinosama** [comment]
> There's not out of the box. It might be a good option. That said, you could fairly easily create a custom formatter:
> 
> ```ruby
> require 'gruf'
> 
> class MyCustomFormatter < Gruf::Interceptors::Instrumentation::RequestLogging::Formatters::Base
>   def format(payload)
>     # do custom payload things here
>     payload.merge!(format: 'json')
>     payload.to_json
>   end
> end
> 
> Gruf.configure do |c|
>   c.interceptors.use(
>     Gruf::Interceptors::Instrumentation::RequestLogging::Interceptor,
>     formatter: MyCustomFormatter
>   )
> end
> ```

Thanks for the quick response/result. Though in my use case, I actually need to insert data from the response instead of simple static values. 

A good example of what I’m looking for is the custom_payload option for lograge:

Rails.application.configure do
  config.lograge.enabled = true

  config.lograge.custom_payload do |controller|
    {
      host: controller.request.host,
      user_id: controller.current_user.try(:id)
    }
  end
end

**Comment by splittingred** [comment]
Got it. There's a couple of ways we could solve this:

* Create another configuration option that allows a block to be passed.
* Pass the request object into formatters to allow them access.

I think i'd prefer the latter, as that doesn't introduce a new abstraction layer or configuration element, and allows custom formatters more flexibility and options when dealing with data. Thoughts?

**Comment by zinosama** [comment]
> Got it. There's a couple of ways we could solve this:
> 
> * Create another configuration option that allows a block to be passed.
> * Pass the request object into formatters to allow them access.
> 
> I think i'd prefer the latter, as that doesn't introduce a new abstraction layer or configuration element, and allows custom formatters more flexibility and options when dealing with data. Thoughts?

I agree the latter is a better approach. It'd be weird to have gruf config options that are specific to an optional interceptor. Thanks for the quick response and getting this into PR.
