### ISSUE TITLE
Service health check

### ISSUE THREAD

**Issue by alikinir** [bigcommerce/gruf#98]
Can be very useful to add documentation / support for grpc health check according to : https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/

**Comment by chrisjeon** [comment]
Yes, please.

**Comment by splittingred** [comment]
@alikinir @chrisjeon I believe all you need to do is generate a gRPC Stub based on: https://github.com/grpc/grpc/blob/master/doc/health-checking.md#service-definition

And then serve it in your application, pointing your service discovery / scheduler to whatever port/host you're serving it on. Gruf is agnostic to service health/discovery; it only serves gRPC services. The gRPC Health Check is just a standardized gRPC service stub.

LMK if you'd like more specific info here. Thanks!
